---

# ToDo:
#  * onepassword

# Setup my home dir
 - import_tasks: "home.yml"   
# install regolith
 - name: add regolith apt ppa apt repository
   apt_repository:
     repo: ppa:regolith-linux/release
     state: present
 - name: install regolith-desktop
   apt:
     name: regolith-desktop
     state: present
 # ToDo: move from just installing to managing all indicators (i.e., remove
 # unmanaged indicators from current use, and add indicators to bar in order
 # specified).
 - name: install i3xrocks menu bar indicators
   apt:
     name: "{{i3_status_packages}}"
     state: present

 - name: Setup snap
   apt:
     name: snapd
     state: present

 - name: Install various snaps
   snap:
       name: "{{ snaps }}"
       state: present

 - name: Install snaps which require classic containment
   snap:
     name: "{{ classic_snaps }}"
     classic: yes

# Non apt package prereqs
 - name: install non apt package prereqs
   apt:
     name: ['apt-transport-https', 'ca-certificates', 'gnupg', 'curl']
     state: present

 - name: "install sshd"
   apt:
     name: "openssh-server"
     state: present

 - name: setup sshd service
   service:
    name: sshd
    state: started
    enabled: yes
 # ToDo: Configure sshd
 #       * add localhost ssh pubkey to authorized-keys if VM

# install sublime
#  - ToDo: add keys?

  # ToDo: Make deb repo idempotent
 - name: Add sublime deb repo
   copy:
    content: "deb https://download.sublimetext.com/ apt/stable/"
    dest: /etc/apt/sources.list.d/sublime-text.list 
    mode: 0644

 - name: install Sublime GPG key
   apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present
 - name: install sublime text and merge
   apt:
     name: ["sublime-text", "sublime-merge"]
     update_cache: yes
     state: present

# Docker

 - name: install docker
   apt:
    name: docker.io
    state: present

 - name: install docker SDK
   pip:
     name: docker
     state: present

# Misc Utilities

 - name: "Setup utility packages (apt):"
   apt:
      name: "{{ utility_packages }}"
      state: present

 - name: Setup useful pip packages
   pip:
     name: "{{ pip_packages }}"
     state: present

 - name: Setup some dev/infra/engineering related stuff
   apt:
      name: "{{ dev_engineering_packages }}"
      state: present


# Docker does not have 20.04 repos up yet
# - name: install docker
#   apt:
#     name: ["docker-ce", "docker-ce-cli"]
#     state: present

 - name: "add docker group"
   group:
     name: docker

 - name: "add user {{ me }} to docker group"
   user:
     name: "{{ me }}"
     append: yes
     groups: ["docker"]

 - name: setup docker service
   service:
    name: docker
    state: started
    enabled: yes

 - import_tasks: "gcp_sdk.yml"
 - import_tasks: "terraform.yml"
 - import_tasks: "aws.yml"
 - import_tasks: "python.yml"
