# Install and setup terraform
 - name: Add Terraform GPG key
   apt_key:
     url: https://apt.releases.hashicorp.com/gpg
     state: present

 - name: Add Terraform repo
   apt_repository:
      repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main"
      state: present
 - name: Install Terraform
   apt:
    name: terraform
    state: present
    update_cache: yes
