me: tjachetta
i3_status_packages:
  - "i3xrocks-battery"
  - "i3xrocks-time"
  - "i3xrocks-wifi"
  - "i3xrocks-media-player"
  - "i3xrocks-volume"
utility_packages:
  # sshd gets its own setup
  - net-tools
  - arp-scan
dev_engineering_packages:
    # Docker isn't in here because we manually manage docker
  - go
  - git
cosmetic_packages:
  - fonts-inconsolata
google_cloud_version: "313.0.1"
# hella gross that I'm hardcoding home in, should learn how to do this
# better, there almost certainly has to be a way.
user_bin_dir: /home/tjachetta/bin