me: tjachetta
my_shell: "/bin/zsh"
i3_status_packages:
  - "i3xrocks-battery"
  - "i3xrocks-time"
  - "i3xrocks-wifi"
  - "i3xrocks-media-player"
  - "i3xrocks-volume"
utility_packages:
  # sshd gets its own setup
  # snap (`snapd`) also gets its own setup
  - net-tools
  - arp-scan
  - zip
  - fping
  - zsh
  # Arp, 
  - net-tools
  - jq
  # GFM renderer
  - grip
  # Time tracking base
  - arbtt
# ToDo combine in packages and use a hash there
snaps:
  - yq
  - spotify
classic_snaps:
  - zoom-client
  - slack
pip_packages:
  - fire
  - virtualenvwrapper
dev_engineering_packages:
    # Docker isn't in here because we manually manage docker
  - go
  - git
  # poetry for python packaging and shit
  # curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
cosmetic_packages:
  - fonts-inconsolata
google_cloud_version: "313.0.1"
# hella gross that I'm hardcoding home in, should learn how to do this
# better, there almost certainly has to be a way.
user_bin_dir: /home/tjachetta/bin`
user_dir: /home/tjachetta

sh_aliases:
  # ToDo
  ansifact: "ansible --help"

# ToDo get some software and install from github
github_packages:
  - square/certigo `(go get -u github.com/square/certigo)`
